[package]
authors = ["danite <luansnain@gmail.com>"]
edition = "2018"
name = "nain"
version = "0.1.0"

[lib]
crate-type = ["lib"]

[workspace]
members = ["sandbox", "crates/*"]

[dependencies]
nain_log = {path = "crates/nain_log"}
nain_events = {path = "crates/nain_events"}
