[package]
authors = ["danite <luansnain@gmail.com>"]
edition = "2018"
name = "nain_log"
version = "0.1.0"

[dependencies]
log = {version = "0.4", features = ["std", "serde"]}
fern = { version = "0.6.0", features = ["colored"] }
chrono = "0.4"
